services:

  datomic-storage:
    image: postgres:16.4-bookworm
    environment:
      POSTGRES_DB: my-datomic-storage
      POSTGRES_USER: datomic-user
      POSTGRES_PASSWORD: unsafe
    ports:
      - '5432:5432'

  datomic-transactor:
    build: ./docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/postgresql/config.edn
    volumes:
      - ./config:/usr/config
    ports:
      - '4334:4334'

  datomic-peer-server:
    build: ./docker/peer-server
    environment:
      PORT: 8998

      DATOMIC_ACCESS_KEY: unsafe-key
      DATOMIC_SECRET: unsafe-secret

      DATOMIC_DATABASE: my-datomic-database
      DATOMIC_STORAGE_URI: datomic:sql://my-datomic-database?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe

      # DATOMIC_DATABASE_2: my-datomic-database-purple
      # DATOMIC_STORAGE_URI_2: datomic:sql://my-datomic-database-purple?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe

      # DATOMIC_DATABASE_3: my-datomic-database-magenta
      # DATOMIC_STORAGE_URI_3: datomic:sql://my-datomic-database-magenta?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe
    ports:
      - 8998:8998

  datomic-console:
    build: ./docker/console
    environment:
      DB_URI: datomic:sql://?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe
    ports:
      - '8080:8080'

  datomic-flare:
    build: ./docker/flare
    environment:
      FLARE_PORT: 3042
      FLARE_BIND: 0.0.0.0

      FLARE_MODE: peer
      FLARE_PEER_CONNECTION_URI: "datomic:sql://my-datomic-database?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe"

      # FLARE_MODE: client
      # FLARE_CLIENT_ENDPOINT: datomic-peer-server:8998
      # FLARE_CLIENT_SECRET: unsafe-secret
      # FLARE_CLIENT_ACCESS_KEY: unsafe-key
      # FLARE_CLIENT_DATABASE_NAME: my-datomic-database
    ports:
      - 3042:3042

  datomic-tools:
    build: ./docker/tools
